- name: print the play-1 information
  hosts: localhost
  tasks:
  - name: play-1 task-1 information
    ansible.builtin.debug:
      msg: "play-1 tassk-1 here"
  - name: play-1 task-2 information
    ansible.builtin.debug:
      msg: "play-1 tassk-2 here"

- name: print the play-2 information
  hosts: localhost
  tasks: 
  - name: play-2 information
    ansible.builtin.debug:
      msg: "play-2 tassks here"