- name: variables at task level
  hosts: localhost
  vars:
   level: play level
  tasks:
  - name: variable at task level
    vars:
      level: task level
    ansible.builtin.debug:
     msg: "variable access from {{level}}"
    