- name: variable preferences
  hosts: localhost
  # vars: 
  #  Present: from play level 
  # vars_files:
  # - vars.yaml
  # vars_prompt:
  #   name: Present
  #   prompt: please give prompt level
  #   private: false
  tasks:
  - name: Print variable Present info
    # vars: 
    #   Present: from task level
    ansible.builtin.debug:
     msg: "printing the present from variable {{Present}}"



     # 1.argument level
     # 2.task level
     # 3.file level
     # 4.prompt level
     # 5.play level