- name: install and uninstall multy packages
  hosts: web
  become: yes
  tasks:
  - name: install multiple packages
    ansible.builtin.dnf:
    with_items:
      - " {{ item.name }} "
      - " {{ item.state }} "
    loop:
    - { name: mysql,state: latest }
    - { name: nginx,state: latest }
    - { name: postfix,state: abscent }