- name: create user
  hosts: localhost
  tasks:
  - name: check whether expense user or not
    ansible.builtin.command: id expense
    register: user_info
    ignore_errors: true
  
  - name: print the user user information
    ansible.builtin.debug:
      msg: " {{ user_info }}"
    
  - name: create expense user
    ansible.builtin.command: useradd expense
    when: user_info.rc !=0
